import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Tipos de atendimento por CNES, extraídos das planilhas TOMO/RNM/Combo (dados idênticos
 * por estabelecimento nas 3 fontes — mesclados e deduplicados). Import único, sem tela de
 * reimportação: se precisar atualizar, criar nova migration.
 */
const TIPOS_ATENDIMENTO_SEED: Array<[string, string]> = [
    [`0000396`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0000434`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0000477`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0002283`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0002534`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`0003778`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0003786`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0003832`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0004294`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0006157`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`0009709`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`0009776`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`0010499`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0011746`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0011800`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0012556`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0013633`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0014109`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0015334`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0015563`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`0015644`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0017868`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`0019445`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0027014`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`0136581`, "[\"AMBULATORIAL\", \"INTERNACAO\"]"],
    [`0400130`, "[\"AMBULATORIAL\"]"],
    [`2001500`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`2001578`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`2001586`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2002078`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"VIGILANCIA EM SAUDE\"]"],
    [`2006197`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2006448`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2007037`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2012677`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2012685`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\"]"],
    [`2013258`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2014688`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`2019574`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2019647`, "[\"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2020068`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2020076`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"URGENCIA\"]"],
    [`2020645`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2020653`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2077477`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2077485`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2080125`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2080354`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2081490`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2082527`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2085194`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2149990`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2153114`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2165058`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`2167727`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2195453`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2200457`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2232022`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2232995`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2244306`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2248190`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2252694`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2254611`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2261316`, "[\"AMBULATORIAL\", \"SADT\"]"],
    [`2261413`, "[\"AMBULATORIAL\", \"SADT\"]"],
    [`2261456`, "[\"OUTROS\", \"REGULACAO\", \"VIGILANCIA EM SAUDE\"]"],
    [`2269775`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"VIGILANCIA EM SAUDE\"]"],
    [`2269821`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2269880`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2269899`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2269988`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"VIGILANCIA EM SAUDE\"]"],
    [`2287447`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2313367`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2315793`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2328402`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`2329905`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`2334321`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2338351`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2376334`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2384779`, "[\"AMBULATORIAL\", \"SADT\"]"],
    [`2385643`, "[\"SADT\"]"],
    [`2396866`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2399741`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2400693`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2402076`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2409194`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2414244`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2436469`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2442108`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2445204`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2470748`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"URGENCIA\"]"],
    [`2497654`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2506815`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2525933`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2528843`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2534444`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2561840`, "[\"AMBULATORIAL\"]"],
    [`2577623`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2600536`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`2600714`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`2601680`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2605473`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2639262`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2646536`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`2651394`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2653923`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2655411`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2655519`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2676060`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2688689`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2691841`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2693801`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2697041`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2697696`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2708779`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2723220`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2726653`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2726998`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2740338`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2761203`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2777460`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`2781859`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2786117`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2795671`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2798298`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2802104`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`2806215`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`2962403`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`3021114`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`3210243`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`3508528`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`3675580`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`3972925`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`4001303`, "[\"INTERNACAO\", \"SADT\"]"],
    [`4009444`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`4026896`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`4028155`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`4305183`, "[\"AMBULATORIAL\", \"URGENCIA\"]"],
    [`4394445`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`4527372`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"URGENCIA\"]"],
    [`4963938`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`4966279`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"URGENCIA\"]"],
    [`5336171`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`5585422`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\"]"],
    [`5616298`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`5922402`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`6201059`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"URGENCIA\"]"],
    [`6322433`, "[\"AMBULATORIAL\"]"],
    [`6602533`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`6779522`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`6817866`, "[\"AMBULATORIAL\"]"],
    [`6848710`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`6926401`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`7047428`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`7061021`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\"]"],
    [`7469683`, "[\"AMBULATORIAL\"]"],
    [`7498810`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`7561571`, "[\"AMBULATORIAL\", \"SADT\"]"],
    [`7564546`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\"]"],
    [`7845138`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"URGENCIA\"]"],
    [`7853688`, "[\"AMBULATORIAL\"]"],
    [`7891067`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"SADT\", \"URGENCIA\", \"VIGILANCIA EM SAUDE\"]"],
    [`7895631`, "[\"AMBULATORIAL\"]"],
    [`9042571`, "[\"AMBULATORIAL\"]"],
    [`9262407`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"URGENCIA\"]"],
    [`9472339`, "[\"AMBULATORIAL\", \"INTERNACAO\", \"REGULACAO\", \"SADT\", \"VIGILANCIA EM SAUDE\"]"],
];

export class CreateHospitalTipoAtendimento1700000056000 implements MigrationInterface {
    async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "hospital_tipo_atendimento" (
                "id" SERIAL PRIMARY KEY,
                "cnes" VARCHAR(7) NOT NULL UNIQUE,
                "tipos" JSONB NOT NULL,
                "created_at" TIMESTAMP NOT NULL DEFAULT now()
            )
        `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_hospital_tipo_atendimento_cnes" ON "hospital_tipo_atendimento" ("cnes")`);

        const existing = await queryRunner.query(`SELECT COUNT(*)::int AS count FROM "hospital_tipo_atendimento"`);
        if (existing[0]?.count === 0) {
            for (const [cnes, tiposJson] of TIPOS_ATENDIMENTO_SEED) {
                await queryRunner.query(
                    `INSERT INTO "hospital_tipo_atendimento" ("cnes", "tipos") VALUES ($1, $2::jsonb)`,
                    [cnes, tiposJson],
                );
            }
        }
    }

    async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS "hospital_tipo_atendimento"`);
    }
}
